// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBB99wFRRfzBSpI1Qc6PWPXTW4iQDzYlA',
    appId: '1:785767673122:web:9bebf9be2975015a2e497b',
    messagingSenderId: '785767673122',
    projectId: 'linkat-center',
    authDomain: 'linkat-center.firebaseapp.com',
    storageBucket: 'linkat-center.appspot.com',
    measurementId: 'G-KCCGYD7QGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyDzdW-FkWeQoXOj4Ya4Lr1PoYydjnXfI',
    appId: '1:785767673122:android:fb063344709f92492e497b',
    messagingSenderId: '785767673122',
    projectId: 'linkat-center',
    storageBucket: 'linkat-center.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ09PO-knzxzpLZGkrDLUqxKUKYtgAi9I',
    appId: '1:785767673122:ios:13b1468cd160d66d2e497b',
    messagingSenderId: '785767673122',
    projectId: 'linkat-center',
    storageBucket: 'linkat-center.appspot.com',
    iosBundleId: 'com.example.linkatCenterDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ09PO-knzxzpLZGkrDLUqxKUKYtgAi9I',
    appId: '1:785767673122:ios:13b1468cd160d66d2e497b',
    messagingSenderId: '785767673122',
    projectId: 'linkat-center',
    storageBucket: 'linkat-center.appspot.com',
    iosBundleId: 'com.example.linkatCenterDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBB99wFRRfzBSpI1Qc6PWPXTW4iQDzYlA',
    appId: '1:785767673122:web:e3c58c8eee11fd612e497b',
    messagingSenderId: '785767673122',
    projectId: 'linkat-center',
    authDomain: 'linkat-center.firebaseapp.com',
    storageBucket: 'linkat-center.appspot.com',
    measurementId: 'G-JWKRX1DCHL',
  );

}